drop table if exists mvp_candidates, teams;

CREATE TABLE IF NOT EXISTS teams (
	team_id VARCHAR(3) PRIMARY KEY,
	ranking INT NOT NULL,
	conference VARCHAR(4) NOT NULL,
	team_name VARCHAR(50) NOT NULL,
	wins INT NOT NULL,
	losses INT NOT NULL,
	win_loss_pct NUMERIC NOT NULL,
	gb NUMERIC,
	ppg NUMERIC NOT NULL,
	opponent_ppg NUMERIC NOT NULL,
	ppg_difference NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS mvp_candidates (
	player_id INT PRIMARY KEY,
	team VARCHAR(3) NOT NULL,
	player_name VARCHAR(50) NOT NULL,
	age INT NOT NULL,
	gp INT NOT NULL,
	gs INT NOT NULL,
	mp NUMERIC NOT NULL,
	fg NUMERIC NOT NULL,
	fga NUMERIC NOT NULL,
	fg_pct NUMERIC NOT NULL,
	three_point NUMERIC NOT NULL,
	three_pa NUMERIC NOT NULL,
	three_pct NUMERIC NOT NULL,
	two_point NUMERIC NOT NULL,
	two_pa NUMERIC NOT NULL,
	two_pct NUMERIC NOT NULL,
	eFG_pct NUMERIC NOT NULL,
	ft NUMERIC NOT NULL,
	fta NUMERIC NOT NULL,
	ft_pct NUMERIC NOT NULL,
	orb NUMERIC NOT NULL,
	drb NUMERIC NOT NULL,
	trb NUMERIC NOT NULL,
	ast NUMERIC NOT NULL,
	stl NUMERIC NOT NULL,
	blk NUMERIC NOT NULL,
	tov NUMERIC NOT NULL,
	pf NUMERIC NOT NULL,
	ppg NUMERIC NOT NULL,
	CONSTRAINT fk_team
		FOREIGN KEY(team) 
			REFERENCES teams (team_id)
);